
version: 2

models:
  - name: stg_games
    description: "Staging table to grab all the top level fields from the raw_games table."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

